# Generated by Django 2.2.7 on 2019-11-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='informativos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField(verbose_name='Informativos')),
                ('arquivo', models.FileField(upload_to='Documentos')),
            ],
        ),
    ]
