# Generated by Django 2.2.7 on 2019-12-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informativo', '0002_auto_20191206_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informativos',
            name='nome',
            field=models.CharField(default=None, max_length=128, verbose_name='nome'),
            preserve_default=False,
        ),
    ]
